### ISSUE TITLE
RuntimeError: Given input size: (576x48x48). Calculated output size: (576x0x0). Output size is too small

### ISSUE THREAD

**Issue by kukby** [Tramac/mobilenetv3-segmentation#6]
Hello Think for your job. When I use your code i meet a question:
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    trainer.train()
  File "train.py", line 182, in train
    outputs = self.model(images)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kukby/mobilenetv3-segmentation-master/core/model/segmentation.py", line 23, in forward
    x = self.head(c4)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kukby/mobilenetv3-segmentation-master/core/model/segmentation.py", line 42, in forward
    x = self.lr_aspp(x)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kukby/mobilenetv3-segmentation-master/core/model/segmentation.py", line 67, in forward
    feat2 = self.b1(x)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kukby/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 554, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (576x48x48). Calculated output size: (576x0x0). Output size is too small

**Comment by Aitical** [comment]
@kukby You can check the [Lite R-ASPP](https://github.com/Tramac/mobilenetv3-segmentation/blob/ca7ec6633e7f75893cf243878b53c4c51366e6ad/core/model/segmentation.py#L59) module in your training code. The origin LRASPP in the project is defined with fixed parameters for the standard mobilenet-v3 processing and you should change the size params to adapt your training input size.

**Comment by dscarmo** [comment]
I was able to fix this by using AdaptiveAvgPooling instead of AvgPool in the LRASPP implementation.

**Comment by adikrishnanucd** [comment]
> I was able to fix this by using AdaptiveAvgPooling instead of AvgPool in the LRASPP implementation.

What did you pass in as your output size for the parameter to AdaptiveAvgPooling?

**Comment by adikrishnanucd** [comment]
@dscarmo what did you pass in as your output size for the AdaptiveAvgPooling parameter?

**Comment by dscarmo** [comment]
> @dscarmo what did you pass in as your output size for the AdaptiveAvgPooling parameter?

To get a single value for each channel you need to pass 1

**Comment by adikrishnanucd** [comment]
@dscarmo thank you very much.
